# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Serhii Trotsenko
title: Web developer
email: sergh.vanger@gmail.com
phone: 380962333805
# website: https://github.com/Vanger888

# Dark Mode (true/false/never)
darkmode: true

# Social links
github_username: vanger888
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: serhii_trotsenko
linkedin_username: serhii-trotsenko-295a6117a
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000
print_link: true

# Additional icon links
additional_links:
# - title: Print CV
#   icon: fas fa-print
#   url: javascript:(print());
#   target: _self
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile-avatar.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Serhii and I'm a frontend web developer. As well as creating static pages I also have experience making SSR sites and SPA/PWA web apps. I have worked at a several companies gaining teamwork and leadership skills.

  I am most skilled in: <mark>Javascript</mark> <mark>HTML</mark> and <mark>CSS</mark>

  Working with <mark>Vue</mark> <mark>Vuex</mark> <mark>TypeScript</mark> <mark>Webpack</mark> <mark>SCSS</mark> <mark>Bootstrap</mark> <mark>Jira</mark>

content:
  # - title: Projects # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: top-middle
  #       title: SportCaller
  #       link: https://sportcaller.com/
  #       # link_text: Project Website
  #       # additional_links:
  #       #   - title:  sproogen/modern-resume-theme
  #       #     icon: fab fa-github
  #       #     url: github.com/sproogen/modern-resume-theme
  #         # - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #         #   icon: fab fa-github
  #         #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
  #       quote: >
  #         August 2020 - now
  #       description: | # this will include new lines to allow paragraphs
  #        The SportCaller platform is an enterprise software solution, used by some of the largest betting and media companies as a key customer acquisition and retention tool. We creating free-to-play games, customized for each client needs. The development team consists of more than 25 people, including 8 front-end developers.

  - title: Experience - 2 years and 3 months # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: SportCaller
        link: https://sportcaller.com
        sub_title: Frontend developer
        caption: August 2020 - Present
        quote: >
          The SportCaller platform is an enterprise software solution, used by some of the largest betting and media companies as a key customer acquisition and retention tool. We creating free-to-play games, customized for each client needs
        description: | # this will include new lines to allow paragraphs
          We creating free-to-play games, customized for each client needs. The development team consists of more than 25 people, including 8 front-end developers. My responsibilities include regular code reviews, development of new client applications, My responsibilities include regular code reviews, developing new client applications, helping newly arrived developers.

      - layout: left
        title: Swagbucks
        link: https://www.swagbucks.com
        # link_text: boringcompany.com
        sub_title: Frontend developer
        caption: November 2019 - August 2020
        quote: >
          Swagbucks is a rewards and loyalty-programs website, launched in 2008, operated by Prodege, LLC, based in El Segundo, California.
        description: | # this will include new lines to allow paragraphs
          My tasks included creating new pages and improving the existing UI/UX. Along with performing business tasks, we implemented new technologies and rewrote legacy code. The project has well-established development processes and high quality code review. The team consisted of up to 6 frontend developers.

      - layout: left
        title: Pumped
        link: https://www.pumped.ai
        # link_text: boringcompany.com
        sub_title: Frontend developer
        caption: March 2019 - October 2019
        quote: >
          Pumped is a startup focused on the US market, the purpose of which is to create a convenient application for buying fuel and refueling, without reference to the specific gas station network.
        description: | # this will include new lines to allow paragraphs
          My first commercial project, where I build PWA application with SSR(Vue + Nuxt.js). I started as junior developer. My responsibilities included creating new components and friendly UI. It was a small frontend team - me and my mentor.

  # - title: Education # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: left
  #       title: Harvard University
  #       caption: 2010 - 2013
  #       sub_title: BSc Computer Science
  #       quote: >
  #         Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
  #       description: | # this will include new lines to allow paragraphs
  #         During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

  #         I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      I am a friendly person with a strong sense of responsibility and attention to detail.

      English level - <mark>Intermediate</mark>

      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Travelling
      - Reading
      - Sport
      - RPG Board Games
      - Poker

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
